name: Bump version and create release

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-and-push.yml

env:
  REGISTRY_IMAGE: nvitaterna/chisel-nodejs-base
  # https://github.com/orgs/community/discussions/27194
  # cannot trigger another action from secrets.GITHUB_TOKEN
  GITHUB_TOKEN: ${{ secrets.PAT }}

concurrency: production
jobs:
  tagAndRelease:
    name: Tag and create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ env.GITHUB_TOKEN }}
