name: Build and test Docker image

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

env:
  REGISTRY_IMAGE: nvitaterna/chisel-nodejs-base

jobs:
  build:
    runs-on: ubuntu-latest
    name: Multiplatform build and test
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: ${{ matrix.platform }}
          # check default scope cache, then check for release scope cache
          cache-from: |
            type=gha
            type=gha,scope=release-${{matrix.platform}}
          # cache to default scope
          cache-to: |
            type=gha,mode=max

      # todo
      # - name: Test
